### PR TITLE
LPS-154230 Fix unit test, test both enabled and disabled.

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by heiditrindade** [comment]
Just starting reviewing :)

**Comment by lucasmiranda0** [comment]
Just starting reviewing :)

**Comment by vngoliveira** [comment]
Just starting reviewing :)

**Comment by MGabriellaS** [comment]
Just starting reviewing :)

**Comment by larissacribeiro** [comment]
Just starting reviewing :)

**Comment by diogomelo09** [comment]
Just starting reviewing :)

**Comment by prokofitch** [comment]
Just starting reviewing :)

**Comment by itstali** [comment]
Just starting reviewing :)

**Comment by ericthmoritsuka** [comment]
Just starting reviewing :)

**Comment by Artartur** [comment]
Just starting reviewing :)

**Comment by manuelecastro** [comment]
Just starting reviewing :)

**Comment by devpedrotavares** [comment]
Just starting reviewing :)

**Comment by danielCamara02** [comment]
Just starting reviewing :)

**Comment by kiwm** [comment]
Just starting reviewing :)

**Comment by deborasoliveira** [comment]
Just starting reviewing :)

**Pull request closed without merging**
